In [ ]:
import pandas as pd
pd.__version__

'2.2.2'

In [ ]:
pd.read_excel("student.xlsx")

In [ ]:
df = pd.read_excel("student.xlsx")
# df is short for dataframe.
# this code will save student file in df

#Inspecting and Exploring DataFrame

In [ ]:
df.head()
#Top 5 rows / by default returns 5 rows
# putting number in the brackets return that number rows

In [ ]:
df.head(10)
#Top 10 rows

In [ ]:
df.tail()
# Returns the last 5 rows in dataset

In [ ]:
df.tail(7)

In [ ]:
df.sample()

# random sample data/ df.sample(5) return have random data

In [ ]:
df.shape
# Number of rows and columns

(35, 5)

In [ ]:
df.info()
# difference between enteries and non-null values
#oject is string data type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      35 non-null     int64
 1   name    34 non-null     object
 2   class   34 non-null     object
 3   mark    35 non-null     int64
 4   gender  33 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.5+ KB

In [ ]:
df.columns
# returns the name of the columns

Index(['id', 'name', 'class', 'mark', 'gender'], dtype='object')

In [ ]:
df.describe()
#returns only the numerical columns / statastical summary

              id       mark
count  35.000000  35.000000
mean   18.000000  74.657143
std    10.246951  16.401117
min     1.000000  18.000000
25%     9.500000  62.500000
50%    18.000000  79.000000
75%    26.500000  88.000000
max    35.000000  96.000000

In [ ]:
len(df)
#returns number of rows

35

In [ ]:
df.size
# returns rows * columns

175

In [ ]:
df.dtypes
#returns data types of each column

id         int64
name      object
class     object
mark       int64
gender    object
dtype: object

In [ ]:
df.isnull().sum()
#counts number of missing values per column

id        0
name      1
class     1
mark      0
gender    2
dtype: int64

In [ ]:
df["name"]
#returns only name column and rows
#called slicing method

In [ ]:
df.class
#This will fail beacuse class is a reserved keyword in python

In [ ]:
df["gender"]

In [ ]:
df[['gender', 'class','gender']]
# you can return multiple columns
#inner [] is list of the column names.
#outer [] is for slicing

In [ ]:
df["name"].head(3)

In [ ]:
df["mark"].max()

96

In [ ]:
df[["name", "class"]].sample()

#loc and iloc operator

In [ ]:
df.loc[0]

In [ ]:
df.loc[3, "mark"]
#returns rows first and then column labels

np.int64(60)

In [ ]:
df.loc[0:4, "name"]
#returns name of first 5 students

0      John Deo
1      Max Ruin
2        Arnold
3    Krish Star
4     John Mike
Name: name, dtype: object

In [ ]:
df.loc[11:15, ["name", "class"]]

        name  class
11     Recky    Six
12       Kty  Seven
13      Bigy  Seven
14  Tade Row    NaN
15     Gimmy   Four

In [ ]:
df.iloc[0,1]
#for iloc the index of the column is written instead of name of the column(which is loc)

'John Deo'

In [ ]:
df.iloc[11:15, 0:2]

In [ ]:
df[df["mark"]>=90]

In [ ]:
df[~(df["class"]=="Five")]

In [ ]:
df[(df["gender"]=="female") | (df["class"]=="Four")]

In [ ]:
df.loc[df["mark"]>=90, :]

In [ ]:
df.loc[(df["gender"] == "female") & (df["class"] == "Four"), :]

In [ ]:
df.filter(like = 'ma')
#filter column names

In [ ]:
df.query('gender == "male"')

#Sort Values

In [ ]:
df.loc[:,:].sort_values(by="name")

In [ ]:
df.loc[:,:].sort_values(by="mark", ascending = False).head()

    id         name  class  mark  gender
32  33    Kenn Rein    Six    96  female
11  12        Recky    Six    94  female
31  32    Binn Rott  Seven    90  female
10  11       Ronald    Six    89  female
30  31  Marry Toeey   Four    88    male

In [ ]:
df[["name", "class"]].sort_values(by="class").head()

In [ ]:
## Class and number of student
df["class"].value_counts()

In [ ]:
df.sort_values(by = ["mark", "name"], ascending=[False, True]).head()

In [ ]:
df["gender"].value_counts()

gender
male      17
female    16
Name: count, dtype: int64

In [ ]:
for i in range(1, 101):
    if i % 3 == 0 and i % 5 == 0:
        print("fizzbuzz")
    elif i % 3 == 0:
        print("fizz")
    elif i % 5 == 0:
        print("buzz")
    else:
        print(i)

1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizzbuzz
16
17
fizz
19
buzz
fizz
22
23
fizz
buzz
26
fizz
28
29
fizzbuzz
31
32
fizz
34
buzz
fizz
37
38
fizz
buzz
41
fizz
43
44
fizzbuzz
46
47
fizz
49
buzz
fizz
52
53
fizz
buzz
56
fizz
58
59
fizzbuzz
61
62
fizz
64
buzz
fizz
67
68
fizz
buzz
71
fizz
73
74
fizzbuzz
76
77
fizz
79
buzz
fizz
82
83
fizz
buzz
86
fizz
88
89
fizzbuzz
91
92
fizz
94
buzz
fizz
97
98
fizz
buzz